services:
  #### stocks: ####
  stocks:
    build:
      context: ./stocks
      dockerfile: Dockerfile
    container_name: stocks
    ports:
      - "5001:8000" # Map host port 5001 to container port 8000
    expose:
      - 8000
    environment:
      - DATABASE_NAME=stocks
      - SERVICE_TYPE=stocks
      - STOCK_SERVICE_PORT=8000 # Set the port as an environment variable for the app
      - MONGODB_URI=mongodb://mongo:27017/stocks
    depends_on:
      - mongo
    volumes:
      - ./shared:/app/shared
    restart: always

  #### mongo: ####  
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017" # Expose MongoDB's default port
    volumes:
      - mongo_data:/data/db # Persistent storage for MongoDB
    restart: always

  #### capital-gains: ####  
  capital-gains-service:
    build: ./capital-gains
    container_name: capital-gains-service
    ports:
      - "5003:8080" # Map host port 5003 to container port 8080
    environment:
      - SERVICE_TYPE=capital-gains
      - CAPITAL_GAIN_SERVICE_PORT=8080
      - STOCKS_SERVICE_URL=http://stocks:8000 # URL for stocks
      - FLASK_APP=app.py
    depends_on:
      - stocks
    volumes:
      - ./shared:/app/shared
    restart: always

volumes:
  mongo_data:
