services:
  #### stocks1: ####
  ### two instances of stocks1 service, these are both the same service, storing and retrieving their data from the same database ###
  stocks1-a:
    build:
      context: ./stocks
      dockerfile: Dockerfile
    container_name: stocks1-a
    ports:
      - "5001:8000" # Map host port 5001 to container port 8000
    expose:
      - 8000
    environment:
      - DATABASE_NAME=stocks
      - SERVICE_TYPE=stocks1
      - STOCK_SERVICE_PORT=8000 # Set the port as an environment variable for the app
      - MONGODB_URI=mongodb://mongo:27017/stocks
    depends_on:
      - mongo
    volumes:
      - ./shared:/app/shared
    restart: always

  stocks1-b:
    # another instance of the stocks1 service for load balancing
    build:
      context: ./stocks
      dockerfile: Dockerfile
    container_name: stocks1-b
    ports:
      - "5004:8000" # Map host port 5001 to container port 8000
    expose:
      - 8000
    environment:
      - DATABASE_NAME=stocks
      - SERVICE_TYPE=stocks1
      - STOCK_SERVICE_PORT=8000 # Set the port as an environment variable for the app
      - MONGODB_URI=mongodb://mongo:27017/stocks

    depends_on:
      - mongo
    volumes:
      - ./shared:/app/shared
    restart: always

  #### stocks2: ####  
  stocks2:
    build:
      context: ./stocks
      dockerfile: Dockerfile
    container_name: stocks2
    ports:
      - "5002:8000" # Map host port 5002 to container port 8000
    expose:
      - 8000
    environment:
      - DATABASE_NAME=stocks
      - SERVICE_TYPE=stocks2
      - STOCK_SERVICE_PORT=8000
      - MONGODB_URI=mongodb://mongo:27017/stocks

    depends_on:
      - mongo
    volumes:
      - ./shared:/app/shared
    restart: always

  #### mongo: ####  
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017" # Expose MongoDB's default port
    volumes:
      - mongo_data:/data/db # Persistent storage for MongoDB
    restart: always

  #### capital-gains: ####  
  capital-gains-service:
    build: ./capital-gains
    container_name: capital-gains-service
    ports:
      - "5003:8080" # Map host port 5003 to container port 8080
    environment:
      - SERVICE_TYPE=capital-gains
      - CAPITAL_GAIN_SERVICE_PORT=8080
      - STOCKS1_SERVICE_URL=http://stocks1-a:8000 # URL for stocks1
      - STOCKS2_SERVICE_URL=http://stocks2:8000 # URL for stocks2
      - FLASK_APP=app.py
    depends_on:
      - stocks1-a
      - stocks2
    volumes:
      - ./shared:/app/shared
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - stocks1-a
      - stocks1-b
      - stocks2
    restart: always



volumes:
  mongo_data:
